### ISSUE TITLE
Questions attempted so far

### ISSUE THREAD

**Issue by simeonhebrew** [Fnyasimi/my-first-repo#25]
https://github.com/simeonhebrew/Code-Exercises

**Comment by Fnyasimi** [comment]
@simeonhebrew Nice work with a few comments
2. Convert it into a script
7. You just copied haha 
11. Leave your raw data raw
12. You don't really need echo. If the lines were 1000 and wanted to read them in chunks what will be the addition?
13.  Will not work if a sequence happens to have space by mistake improve on the approach
